name: Deploy React to S3 + CloudFront

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: deploy-main
  cancel-in-progress: true

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  CLOUDFRONT_DISTRIBUTION_ID: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
  DEPLOYER_ROLE: ${{ vars.DEPLOYER_ROLE }}
  BUILD_DIR: dist

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          CI: "false"
        run: npm run build

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.DEPLOYER_ROLE }}
          role-session-name: github-actions-deploy

      - name: Upload static assets with long cache
        run: |
          # Upload everything EXCEPT index.html with long, immutable cache
          aws s3 sync "$BUILD_DIR" "s3://${S3_BUCKET}" \
            --delete \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable"

      - name: Upload index.html with no-cache
        run: |
          aws s3 cp "$BUILD_DIR/index.html" "s3://${S3_BUCKET}/index.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" \
            --paths "/*"
